# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds and Uploads App to HockeyApp"
  lane :beta do
    increment_build_number
  	[["Bump", "Release"]].each do |scheme_name, configuration|
  		gym(
			scheme: scheme_name,
  			configuration: configuration,
			export_method: "ad-hoc"
    	)
	
		hockey(
      		api_token: "39260d7d0f854f0880c7ef5532a0daa0"
    	)
  	end
  end

  lane :build do |options|
    gym(
      scheme: "Bump",
      configuration: "Release",
      export_method: "ad-hoc",
      export_options: { compileBitcode: false }
    )

    upload_to_appcenter(app_name: "Ciao")
  end

  lane :travis_beta do
    setup_travis
    # ensure_git_status_clean
    match(type: "adhoc", readonly: is_ci)
    # build_number = increment_build_number(xcodeproj: "Restaurant.xcodeproj")
    # # Commit the version bump, skipping CI Build
    # commit_version_bump(xcodeproj: "Restaurant.xcodeproj", message:"chore(project): update build to #{build_number} [ci skip]")
    # # Push new build number
    # push_to_git_remote(tags: false)
    build
  end

  lane :upload_to_appcenter do |options|
    appcenter_upload(
      api_token: "5e0b943058bdb7eec030b82b8c216bd609cf385b",
      owner_name: "tjwio",
      app_name: options[:app_name],
      ipa: "./Bump.ipa",
      dsym: "./Bump.app.dSYM.zip",
      destinations: "Internal",
      notify_testers: true
    )
  end
end
